<a href="https://colab.research.google.com/github/IgorMatias04/AulasIA09/blob/main/AulaIA09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
clima=['Ensolarado', 'Ensolarado', 'Nublado', 'Chuvoso', 'Chuvoso', 'Chuvoso', 'Nublado',
'Ensolarado', 'Ensolarado', 'Chuvoso', 'Ensolarado', 'Nublado', 'Nublado', 'Chuvoso']

temp=['Quente', 'Quente', 'Quente', 'Suave', 'Legal', 'Legal', 'Legal', 'Suave',
'Legal', 'Suave', 'Suave', 'Suave', 'Quente', 'Suave']

brincar=['Não','Não','Sim','Sim','Sim','Não','Sim','Não','Sim','Sim','Sim','Sim','Sim','Não']

In [ ]:
from sklearn import preprocessing

In [ ]:
le = preprocessing.LabelEncoder()

In [ ]:
clima_encoded = le.fit_transform(clima)
temp_encoded = le.fit_transform(temp)
print(clima_encoded)
print(temp_encoded)

[1 1 2 0 0 0 2 1 1 0 1 2 2 0]
[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


In [ ]:
alvo = le.fit_transform(brincar)
print(alvo)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
carac=list(zip(clima_encoded,temp_encoded))
carac

[(1, 1),
 (1, 1),
 (2, 1),
 (0, 2),
 (0, 0),
 (0, 0),
 (2, 0),
 (1, 2),
 (1, 0),
 (0, 2),
 (1, 2),
 (2, 2),
 (2, 1),
 (0, 2)]

In [ ]:
#Importa a biblioteca do modelo Naive Bayes Gaussiano
from sklearn.naive_bayes import GaussianNB
import numpy as np
#Cria um classificador Gaussiano
modelo = GaussianNB()
# Treinando o modelo usando os ajustes de treinamento.
modelo.fit(carac,alvo)
#Predito
predito = modelo.predict([[2,2]]) # 2:Nublado, 2:Suave
print(predito)

[1]
